development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: okiereview_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
    adapter: mysql
    encoding: utf8
    reconnect: false
    database: okiereview_test
    pool: 5
    username: root
    password:
    socket: /tmp/mysql.sock
production:
    adapter: mysql
    encoding: utf8
    reconnect: false
    database: okiereview_production
    pool: 5
    username: root
    password:
    socket: /tmp/mysql.sock